" Generated by vim-plug
" 六  4/ 9 09:32:29 2016
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ctrlp.vim'].commit = '564176f'
silent! let g:plugs['vim-airline'].commit = '168dd79'
silent! let g:plugs['vim-airline-themes'].commit = 'a59cea9'
silent! let g:plugs['vim-jsx'].commit = '2bd9126'

PlugUpdate!

